"""Colormap module compatibility stub for matplotlib.cm."""


def get_cmap(name='viridis', lut=None):
    """Get a colormap by name (returns the name string as a stub)."""
    return name


# Common colormaps as attributes
viridis = 'viridis'
plasma = 'plasma'
inferno = 'inferno'
magma = 'magma'
cividis = 'cividis'
twilight = 'twilight'
turbo = 'turbo'
hot = 'hot'
cool = 'cool'
gray = 'gray'
grey = 'gray'
jet = 'jet'
spring = 'spring'
summer = 'summer'
autumn = 'autumn'
winter = 'winter'
bone = 'bone'
copper = 'copper'
pink = 'pink'
binary = 'binary'
ocean = 'ocean'
terrain = 'terrain'
Blues = 'Blues'
Reds = 'Reds'
Greens = 'Greens'
Oranges = 'Oranges'
Purples = 'Purples'
YlOrRd = 'YlOrRd'
YlGnBu = 'YlGnBu'
RdYlBu = 'RdYlBu'
RdBu = 'RdBu'
PiYG = 'PiYG'
PRGn = 'PRGn'
BrBG = 'BrBG'
Spectral = 'Spectral'
coolwarm = 'coolwarm'
bwr = 'bwr'
seismic = 'seismic'
Set1 = 'Set1'
Set2 = 'Set2'
Set3 = 'Set3'
Pastel1 = 'Pastel1'
Pastel2 = 'Pastel2'
tab10 = 'tab10'
tab20 = 'tab20'
tab20b = 'tab20b'
tab20c = 'tab20c'
