from typing import Optional, Union, Tuple, List, Any
import numpy as np

def plot(*args: Any, **kwargs: Any) -> None: ...
def scatter(x: Any, y: Any, **kwargs: Any) -> None: ...
def bar(x: Any, height: Any, **kwargs: Any) -> None: ...
def barh(y: Any, width: Any, **kwargs: Any) -> None: ...
def hist(x: Any, **kwargs: Any) -> None: ...
def imshow(data: Any, **kwargs: Any) -> None: ...
def fill_between(x: Any, y1: Any, y2: Any = ..., **kwargs: Any) -> None: ...
def errorbar(x: Any, y: Any, **kwargs: Any) -> None: ...
def step(x: Any, y: Any, **kwargs: Any) -> None: ...
def pie(sizes: Any, **kwargs: Any) -> None: ...
def boxplot(data: Any, **kwargs: Any) -> None: ...
def stem(x: Any, y: Any, **kwargs: Any) -> None: ...
def contour(*args: Any, **kwargs: Any) -> None: ...
def contourf(*args: Any, **kwargs: Any) -> None: ...
def hexbin(x: Any, y: Any, **kwargs: Any) -> None: ...
def quiver(*args: Any, **kwargs: Any) -> None: ...
def streamplot(*args: Any, **kwargs: Any) -> None: ...
def violinplot(data: Any, **kwargs: Any) -> None: ...

def figure(figsize: Optional[Tuple[float, float]] = ..., dpi: int = ..., **kwargs: Any) -> Any: ...
def subplots(nrows: int = ..., ncols: int = ..., figsize: Optional[Tuple[float, float]] = ..., **kwargs: Any) -> Tuple[Any, Any]: ...
def subplot(*args: Any, **kwargs: Any) -> Any: ...
def subplot_mosaic(mosaic: Any, **kwargs: Any) -> Tuple[Any, dict]: ...

def title(text: str, **kwargs: Any) -> None: ...
def xlabel(text: str, **kwargs: Any) -> None: ...
def ylabel(text: str, **kwargs: Any) -> None: ...
def xlim(*args: Any, **kwargs: Any) -> None: ...
def ylim(*args: Any, **kwargs: Any) -> None: ...
def legend(*args: Any, **kwargs: Any) -> None: ...
def grid(visible: bool = ..., **kwargs: Any) -> None: ...
def text(x: float, y: float, s: str, **kwargs: Any) -> None: ...
def annotate(text: str, xy: Any = ..., xytext: Any = ..., **kwargs: Any) -> None: ...
def axhline(y: float = ..., **kwargs: Any) -> None: ...
def axvline(x: float = ..., **kwargs: Any) -> None: ...
def axhspan(ymin: float = ..., ymax: float = ..., **kwargs: Any) -> None: ...
def axvspan(xmin: float = ..., xmax: float = ..., **kwargs: Any) -> None: ...
def colorbar(**kwargs: Any) -> None: ...
def suptitle(t: str, **kwargs: Any) -> None: ...
def tight_layout(**kwargs: Any) -> None: ...
def subplots_adjust(**kwargs: Any) -> None: ...

def savefig(fname: str, **kwargs: Any) -> None: ...
def show() -> None: ...
def close(*args: Any) -> None: ...
def clf() -> None: ...
def cla() -> None: ...
def gcf() -> Any: ...
def gca(**kwargs: Any) -> Any: ...
def draw() -> None: ...
def pause(interval: float) -> None: ...
def ion() -> None: ...
def ioff() -> None: ...

def xscale(scale: str, **kwargs: Any) -> None: ...
def yscale(scale: str, **kwargs: Any) -> None: ...
def semilogy(*args: Any, **kwargs: Any) -> None: ...
def semilogx(*args: Any, **kwargs: Any) -> None: ...
def loglog(*args: Any, **kwargs: Any) -> None: ...

def xticks(ticks: Any = ..., labels: Any = ..., **kwargs: Any) -> None: ...
def yticks(ticks: Any = ..., labels: Any = ..., **kwargs: Any) -> None: ...
def tick_params(**kwargs: Any) -> None: ...
def minorticks_on() -> None: ...
def minorticks_off() -> None: ...

def margins(*args: Any, **kwargs: Any) -> None: ...
def autoscale(enable: bool = ..., axis: str = ..., tight: Optional[bool] = ...) -> None: ...

def hlines(y: Any, xmin: float, xmax: float, **kwargs: Any) -> None: ...
def vlines(x: Any, ymin: float, ymax: float, **kwargs: Any) -> None: ...
def fill_betweenx(y: Any, x1: Any, x2: Any = ..., **kwargs: Any) -> None: ...
def table(**kwargs: Any) -> None: ...

def subplot_polar(**kwargs: Any) -> Any: ...
def axes(arg: Any = ..., **kwargs: Any) -> Any: ...
def figtext(x: float, y: float, s: str, **kwargs: Any) -> None: ...
def figimage(*args: Any, **kwargs: Any) -> None: ...
def figlegend(*args: Any, **kwargs: Any) -> None: ...

def isinteractive() -> bool: ...
def connect(event: str, func: Any) -> None: ...
def disconnect(cid: Any) -> None: ...
def get_fignums() -> List[int]: ...
def figure_exists(num: int) -> bool: ...
def get_current_fig_manager() -> None: ...
def colormaps() -> List[str]: ...
def get_cmap(name: str = ...) -> Any: ...

def switch_backend(backend: str) -> None: ...
def use(backend: str) -> None: ...

rcParams: dict
