"""Type stubs for rustplotlib.pyplot — full matplotlib-compatible API."""
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

# --- Module-level functions ---

def figure(figsize: Optional[Tuple[float, float]] = ..., dpi: int = ..., facecolor: Optional[str] = ..., **kwargs: Any) -> FigureProxy: ...
def subplots(nrows: int = ..., ncols: int = ..., figsize: Optional[Tuple[float, float]] = ..., dpi: int = ..., sharex: bool = ..., sharey: bool = ..., subplot_kw: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Tuple[FigureProxy, Any]: ...
def subplot(*args: Any, **kwargs: Any) -> AxesProxy: ...
def subplot_mosaic(mosaic: Any, figsize: Optional[Tuple[float, float]] = ..., **kwargs: Any) -> Tuple[FigureProxy, Dict[str, AxesProxy]]: ...

def plot(*args: Any, **kwargs: Any) -> List[Line2DProxy]: ...
def scatter(x: Any, y: Any, s: Any = ..., c: Any = ..., marker: str = ..., alpha: float = ..., label: Optional[str] = ..., **kwargs: Any) -> PathCollectionProxy: ...
def bar(x: Any, height: Any, width: float = ..., bottom: Optional[float] = ..., color: Optional[str] = ..., label: Optional[str] = ..., **kwargs: Any) -> Any: ...
def barh(y: Any, width: Any, height: float = ..., **kwargs: Any) -> Any: ...
def hist(x: Any, bins: int = ..., color: Optional[str] = ..., alpha: float = ..., label: Optional[str] = ..., **kwargs: Any) -> Any: ...
def imshow(data: Any, cmap: str = ..., interpolation: Optional[str] = ..., origin: Optional[str] = ..., extent: Optional[Sequence[float]] = ..., **kwargs: Any) -> Any: ...
def contour(*args: Any, **kwargs: Any) -> Any: ...
def contourf(*args: Any, **kwargs: Any) -> Any: ...
def hexbin(x: Any, y: Any, **kwargs: Any) -> Any: ...
def quiver(*args: Any, **kwargs: Any) -> Any: ...
def streamplot(*args: Any, **kwargs: Any) -> Any: ...
def pie(sizes: Any, **kwargs: Any) -> Any: ...
def boxplot(data: Any, **kwargs: Any) -> Any: ...
def violinplot(data: Any, **kwargs: Any) -> Any: ...
def stem(x: Any, y: Any, **kwargs: Any) -> Any: ...
def errorbar(x: Any, y: Any, **kwargs: Any) -> Any: ...
def step(x: Any, y: Any, **kwargs: Any) -> Any: ...
def fill_between(x: Any, y1: Any, y2: Any = ..., **kwargs: Any) -> Any: ...
def fill_betweenx(y: Any, x1: Any, x2: Any = ..., **kwargs: Any) -> Any: ...
def stackplot(x: Any, *args: Any, **kwargs: Any) -> Any: ...
def pcolormesh(*args: Any, **kwargs: Any) -> Any: ...

def colorbar(mappable: Any = ..., **kwargs: Any) -> Any: ...
def legend(*args: Any, **kwargs: Any) -> Any: ...
def title(label: str, fontsize: Optional[float] = ..., **kwargs: Any) -> None: ...
def xlabel(label: str, fontsize: Optional[float] = ..., **kwargs: Any) -> None: ...
def ylabel(label: str, fontsize: Optional[float] = ..., **kwargs: Any) -> None: ...
def xlim(*args: Any) -> Tuple[float, float]: ...
def ylim(*args: Any) -> Tuple[float, float]: ...
def grid(visible: bool = ..., **kwargs: Any) -> None: ...
def text(x: float, y: float, s: str, **kwargs: Any) -> None: ...
def annotate(text: str, xy: Any = ..., xytext: Any = ..., **kwargs: Any) -> None: ...
def axhline(y: float = ..., **kwargs: Any) -> None: ...
def axvline(x: float = ..., **kwargs: Any) -> None: ...
def axhspan(ymin: float = ..., ymax: float = ..., **kwargs: Any) -> None: ...
def axvspan(xmin: float = ..., xmax: float = ..., **kwargs: Any) -> None: ...
def hlines(y: Any, xmin: float, xmax: float, **kwargs: Any) -> None: ...
def vlines(x: Any, ymin: float, ymax: float, **kwargs: Any) -> None: ...
def table(**kwargs: Any) -> None: ...
def suptitle(t: str, fontsize: Optional[float] = ..., **kwargs: Any) -> None: ...
def tight_layout(**kwargs: Any) -> None: ...
def subplots_adjust(**kwargs: Any) -> None: ...

def savefig(fname: str, dpi: Optional[int] = ..., transparent: bool = ..., bbox_inches: Optional[str] = ..., **kwargs: Any) -> None: ...
def show(**kwargs: Any) -> None: ...
def close(fig: Any = ...) -> None: ...
def clf() -> None: ...
def cla() -> None: ...
def gcf() -> FigureProxy: ...
def gca(**kwargs: Any) -> AxesProxy: ...
def draw() -> None: ...
def pause(interval: float) -> None: ...
def ion() -> None: ...
def ioff() -> None: ...

def xscale(scale: str, **kwargs: Any) -> None: ...
def yscale(scale: str, **kwargs: Any) -> None: ...
def semilogy(*args: Any, **kwargs: Any) -> None: ...
def semilogx(*args: Any, **kwargs: Any) -> None: ...
def loglog(*args: Any, **kwargs: Any) -> None: ...

def xticks(ticks: Any = ..., labels: Any = ..., **kwargs: Any) -> None: ...
def yticks(ticks: Any = ..., labels: Any = ..., **kwargs: Any) -> None: ...
def tick_params(**kwargs: Any) -> None: ...
def minorticks_on() -> None: ...
def minorticks_off() -> None: ...

def mpl_connect(event: str, func: Any) -> int: ...
def mpl_disconnect(cid: int) -> None: ...

def switch_backend(backend: str) -> None: ...
def use(backend: str) -> None: ...
def isinteractive() -> bool: ...
def get_fignums() -> List[int]: ...
def colormaps() -> List[str]: ...
def get_cmap(name: str = ...) -> Any: ...

rcParams: Dict[str, Any]

# --- Classes ---

class ArtistBase:
    def set_alpha(self, alpha: float) -> None: ...
    def get_alpha(self) -> float: ...
    def set_visible(self, b: bool) -> None: ...
    def get_visible(self) -> bool: ...
    def set_zorder(self, z: int) -> None: ...
    def get_zorder(self) -> int: ...
    def set_label(self, label: str) -> None: ...
    def get_label(self) -> str: ...
    def set_picker(self, picker: Any) -> None: ...
    def get_picker(self) -> Any: ...
    def pickable(self) -> bool: ...
    def contains(self, mouseevent: Any) -> Tuple[bool, Dict[str, Any]]: ...
    def set_clip_on(self, b: bool) -> None: ...
    def set_clip_box(self, clipbox: Any) -> None: ...
    def set_clip_path(self, path: Any, transform: Any = ...) -> None: ...
    def set_transform(self, t: Any) -> None: ...
    def set_animated(self, b: bool) -> None: ...
    def set_path_effects(self, effects: List[Any]) -> None: ...
    def get_path_effects(self) -> List[Any]: ...
    def get_children(self) -> List[Any]: ...
    def findobj(self, match: Any = ...) -> List[Any]: ...
    def remove(self) -> None: ...
    @property
    def stale(self) -> bool: ...

class Line2DProxy(ArtistBase):
    def set_data(self, x: Any, y: Any) -> None: ...
    def set_color(self, c: str) -> None: ...
    def set_linewidth(self, lw: float) -> None: ...
    def set_linestyle(self, ls: str) -> None: ...
    def get_color(self) -> str: ...
    def get_linewidth(self) -> float: ...
    def get_linestyle(self) -> str: ...
    def get_xdata(self) -> List[float]: ...
    def get_ydata(self) -> List[float]: ...

class PathCollectionProxy(ArtistBase):
    def set_offsets(self, offsets: Any) -> None: ...
    def set_array(self, a: Any) -> None: ...
    def set_clim(self, vmin: float, vmax: float) -> None: ...
    def set_sizes(self, s: Any) -> None: ...
    def set_color(self, c: str) -> None: ...
    def get_offsets(self) -> List[Tuple[float, float]]: ...

class AxesProxy:
    def plot(self, *args: Any, zorder: Optional[int] = ..., path_effects: Optional[List[Any]] = ..., **kwargs: Any) -> List[Line2DProxy]: ...
    def scatter(self, x: Any, y: Any, s: Any = ..., c: Any = ..., marker: str = ..., alpha: float = ..., label: Optional[str] = ..., picker: Any = ..., **kwargs: Any) -> PathCollectionProxy: ...
    def bar(self, x: Any, height: Any, width: float = ..., **kwargs: Any) -> Any: ...
    def barh(self, y: Any, width: Any, **kwargs: Any) -> Any: ...
    def hist(self, x: Any, bins: int = ..., **kwargs: Any) -> Any: ...
    def imshow(self, data: Any, cmap: str = ..., interpolation: Optional[str] = ..., origin: Optional[str] = ..., **kwargs: Any) -> Any: ...
    def contour(self, *args: Any, **kwargs: Any) -> Any: ...
    def contourf(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_title(self, title: str, fontsize: Optional[float] = ..., loc: Optional[str] = ..., **kwargs: Any) -> None: ...
    def set_xlabel(self, label: str, fontsize: Optional[float] = ..., color: Optional[str] = ..., **kwargs: Any) -> None: ...
    def set_ylabel(self, label: str, fontsize: Optional[float] = ..., color: Optional[str] = ..., **kwargs: Any) -> None: ...
    def set_xlim(self, left: Optional[float] = ..., right: Optional[float] = ..., **kwargs: Any) -> Tuple[float, float]: ...
    def set_ylim(self, bottom: Optional[float] = ..., top: Optional[float] = ..., **kwargs: Any) -> Tuple[float, float]: ...
    def get_xlim(self) -> Tuple[float, float]: ...
    def get_ylim(self) -> Tuple[float, float]: ...
    def get_title(self) -> str: ...
    def legend(self, *args: Any, **kwargs: Any) -> Any: ...
    def grid(self, b: bool = ..., **kwargs: Any) -> None: ...
    def set_xscale(self, scale: str) -> None: ...
    def set_yscale(self, scale: str) -> None: ...
    def set_xticks(self, ticks: List[float], labels: Optional[List[str]] = ..., **kwargs: Any) -> None: ...
    def set_yticks(self, ticks: List[float], labels: Optional[List[str]] = ..., **kwargs: Any) -> None: ...
    def colorbar(self, mappable: Any = ..., **kwargs: Any) -> 'AxesProxy': ...
    def add_patch(self, patch: Any) -> Any: ...
    def add_collection(self, collection: Any) -> Any: ...
    def annotate(self, text: str, xy: Tuple[float, float], **kwargs: Any) -> None: ...
    def text(self, x: float, y: float, s: str, **kwargs: Any) -> None: ...
    def axhline(self, y: float = ..., **kwargs: Any) -> None: ...
    def axvline(self, x: float = ..., **kwargs: Any) -> None: ...
    def fill_between(self, x: Any, y1: Any, y2: Any = ..., **kwargs: Any) -> Any: ...
    def twinx(self) -> 'AxesProxy': ...
    def twiny(self) -> 'AxesProxy': ...
    def set_facecolor(self, color: str) -> None: ...
    def set_aspect(self, aspect: Any) -> None: ...
    def invert_xaxis(self) -> None: ...
    def invert_yaxis(self) -> None: ...
    def set(self, **kwargs: Any) -> None: ...
    def clear(self) -> None: ...
    def pick(self, mouseevent: Any) -> None: ...
    @property
    def transData(self) -> Any: ...
    @property
    def transAxes(self) -> Any: ...
    @property
    def spines(self) -> Any: ...

class FigureProxy:
    @property
    def canvas(self) -> Any: ...
    @property
    def transFigure(self) -> Any: ...
    @property
    def dpi(self) -> int: ...
    @property
    def axes(self) -> List[AxesProxy]: ...
    def savefig(self, fname: str, dpi: Optional[int] = ..., transparent: bool = ..., format: Optional[str] = ..., bbox_inches: Optional[str] = ..., **kwargs: Any) -> None: ...
    def set_size_inches(self, w: float, h: Optional[float] = ...) -> None: ...
    def get_size_inches(self) -> Tuple[float, float]: ...
    def suptitle(self, text: str, fontsize: Optional[float] = ..., **kwargs: Any) -> None: ...
    def tight_layout(self, **kwargs: Any) -> None: ...
    def subplots_adjust(self, **kwargs: Any) -> None: ...
    def add_subplot(self, *args: Any, projection: Optional[str] = ..., **kwargs: Any) -> Union[AxesProxy, 'Axes3DProxy']: ...
    def add_axes(self, rect: Sequence[float], **kwargs: Any) -> AxesProxy: ...
    def add_gridspec(self, nrows: int, ncols: int, **kwargs: Any) -> Any: ...
    def colorbar(self, mappable: Any = ..., ax: Any = ..., **kwargs: Any) -> Any: ...
    def show(self, **kwargs: Any) -> None: ...
    def to_json(self) -> str: ...
    def save_json(self, filename: str) -> None: ...
    def text(self, x: float, y: float, s: str, **kwargs: Any) -> None: ...
    def legend(self, *args: Any, **kwargs: Any) -> Any: ...

class Axes3DProxy:
    def plot(self, xs: Any, ys: Any, zs: Any, **kwargs: Any) -> Any: ...
    def scatter(self, xs: Any, ys: Any, zs: Any, **kwargs: Any) -> Any: ...
    def plot_surface(self, X: Any, Y: Any, Z: Any, cmap: str = ..., **kwargs: Any) -> Any: ...
    def plot_wireframe(self, X: Any, Y: Any, Z: Any, **kwargs: Any) -> Any: ...
    def bar3d(self, x: Any, y: Any, z: Any, dx: Any, dy: Any, dz: Any, **kwargs: Any) -> Any: ...
    def view_init(self, elev: float = ..., azim: float = ..., **kwargs: Any) -> None: ...
    def rotate(self, d_azim: float, d_elev: float) -> None: ...
    def set_title(self, title: str, **kwargs: Any) -> None: ...
    def set_xlabel(self, label: str, **kwargs: Any) -> None: ...
    def set_ylabel(self, label: str, **kwargs: Any) -> None: ...
    def set_zlabel(self, label: str, **kwargs: Any) -> None: ...
    def set_xlim(self, left: Optional[float] = ..., right: Optional[float] = ...) -> None: ...
    def set_ylim(self, bottom: Optional[float] = ..., top: Optional[float] = ...) -> None: ...
    def set_zlim(self, bottom: Optional[float] = ..., top: Optional[float] = ...) -> None: ...
